// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpqjbyokxmpusmjpcjdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwcWpieW9reG1wdXNtanBjamR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODM0MjQsImV4cCI6MjA3MTc1OTQyNH0.sRwsUTe4TSLTiglqWSUqG1_cuhNLsiYX3Hc5mhYSWPE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});